import '../../styles/globals.css';

import React from 'react';
import Providers from '../(site)/Providers.js';
import { ChevronLeftIcon } from '@heroicons/react/24/outline';
import Link from 'next/link';
import Sidebar from '../components/dashboardComponents/Sidebar';
import DashboardHeader from '../components/dashboardComponents/DashboardHeader';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

function AuthLayout({ children }) {
  return (
    <html lang='en'>
      <body className='dashboard_newLayout flex h-screen'>
        <Providers>
          <Sidebar />
          <div className='w-[85%] border bg-slate-50'>
            <DashboardHeader />
            <main className=' p-4'>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}

export default AuthLayout;
